name: Build Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 7.2

      - name: Build Android
        run: ./gradlew androidApp:build

      - name: Build iOS
        run: xcodebuild -project iosApp/iosApp.xcodeproj -scheme iosApp -destination 'platform=iOS Simulator,name=iPhone 15' build